"use client";

import { useEffect, useMemo, useState } from "react";
import Link from "next/link";
import QRCodeStyling from "qr-code-styling";
import { Download, ExternalLink, Pencil, Power, Plus, QrCode, Trash2 } from "lucide-react";
import api from "@/lib/axios";

export default function QrCodesPage() {
  const [codes, setCodes] = useState([]); const [loading, setLoading] = useState(true); const [query, setQuery] = useState(""); const [status, setStatus] = useState("all"); const [error, setError] = useState("");
  useEffect(() => { let active = true; api.get("/qr").then(({ data }) => { if (active) setCodes(data.qrCodes || []); }).catch((err) => { if (active) setError(err.response?.data?.message || "Could not load your QR codes."); }).finally(() => { if (active) setLoading(false); }); return () => { active = false; }; }, []);
  const visibleCodes = useMemo(() => codes.filter((code) => (status === "all" || code.status === status) && `${code.name} ${code.type}`.toLowerCase().includes(query.toLowerCase())), [codes, query, status]);
  const update = async (code, patch) => { try { const { data } = await api.patch(`/qr/${code._id}`, patch); setCodes((current) => current.map((item) => item._id === code._id ? data.qrCode : item)); } catch (err) { setError(err.response?.data?.message || "Could not update this QR code."); } };
  const remove = async (code) => { if (!window.confirm(`Delete “${code.name}”? This cannot be undone.`)) return; try { await api.delete(`/qr/${code._id}`); setCodes((current) => current.filter((item) => item._id !== code._id)); } catch { setError("Could not delete this QR code."); } };
  const download = (code) => { const style = code.design || {}; const qr = new QRCodeStyling({ width: 1000, height: 1000, type: "png", data: `${window.location.origin}/r/${code.shortCode}`, dotsOptions: { color: style.patternColor || "#000", type: style.pattern === "dots" ? "dots" : "square" }, backgroundOptions: { color: style.transparentBackground ? "transparent" : style.backgroundColor || "#fff" }, image: style.logo || undefined, imageOptions: { crossOrigin: "anonymous", margin: 12 } }); qr.download({ name: code.name.replace(/[^a-z0-9]+/gi, "-").toLowerCase() || "qr-code", extension: "png" }); };
  return <div className="mx-auto max-w-6xl space-y-7"><div className="flex flex-wrap items-center justify-between gap-4"><div><p className="text-sm font-medium text-emerald-600">Dashboard</p><h1 className="text-3xl font-bold text-slate-900">My QR Codes</h1><p className="mt-1 text-slate-500">Create, download, update, or pause your dynamic QR codes.</p></div><Link href="/qr" className="inline-flex items-center gap-2 rounded-xl bg-[#20c75a] px-5 py-3 font-semibold text-white hover:bg-emerald-600"><Plus size={18} /> Create QR code</Link></div>
    <div className="flex flex-wrap gap-3 rounded-2xl border bg-white p-4 shadow-sm"><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search QR codes…" className="h-11 min-w-56 flex-1 rounded-lg border px-3 outline-none focus:border-emerald-500" /><select value={status} onChange={(event) => setStatus(event.target.value)} className="h-11 rounded-lg border bg-white px-3"><option value="all">All statuses</option><option value="active">Active</option><option value="inactive">Paused</option></select></div>
    {error && <p className="rounded-lg bg-red-50 p-3 text-sm text-red-700">{error}</p>}
    {loading ? <p className="py-20 text-center text-slate-500">Loading your QR codes…</p> : visibleCodes.length ? <div className="grid gap-4 md:grid-cols-2">{visibleCodes.map((code) => <article key={code._id} className="rounded-2xl border bg-white p-5 shadow-sm"><div className="flex justify-between gap-3"><div><span className="rounded-full bg-emerald-50 px-2.5 py-1 text-xs font-semibold capitalize text-emerald-700">{code.type}</span><h2 className="mt-3 font-semibold text-slate-900">{code.name}</h2><a href={`/r/${code.shortCode}`} target="_blank" className="mt-1 inline-flex items-center gap-1 text-sm text-slate-500 hover:text-emerald-600">/r/{code.shortCode}<ExternalLink size={13} /></a></div><span className={`h-fit rounded-full px-2.5 py-1 text-xs font-semibold ${code.status === "active" ? "bg-green-50 text-green-700" : "bg-slate-100 text-slate-600"}`}>{code.status}</span></div><div className="mt-5 flex items-center justify-between border-t pt-4 text-sm text-slate-500"><span>{code.scanCount || 0} scans</span><span>{new Date(code.createdAt).toLocaleDateString()}</span></div><div className="mt-4 flex flex-wrap gap-2"><button onClick={() => download(code)} className="action"><Download size={16} /> Download</button><button onClick={() => update(code, { status: code.status === "active" ? "inactive" : "active" })} className="action"><Power size={16} /> {code.status === "active" ? "Pause" : "Activate"}</button>{code.content?.url && <button onClick={() => { const next = window.prompt("New destination URL", code.content.url); if (next) update(code, { content: { url: next } }); }} className="action"><Pencil size={16} /> Edit link</button>}<button onClick={() => remove(code)} className="action text-red-600 hover:border-red-200 hover:bg-red-50"><Trash2 size={16} /> Delete</button></div></article>)}</div> : <div className="rounded-2xl border border-dashed bg-white px-6 py-20 text-center"><QrCode className="mx-auto mb-4 text-emerald-500" size={42} /><h2 className="text-xl font-semibold text-slate-900">No QR codes yet</h2><p className="mt-2 text-slate-500">Your first dynamic QR code is only a minute away.</p><Link href="/qr" className="mt-5 inline-block font-semibold text-emerald-600">Create a QR code →</Link></div>}</div>;
}
